GET http://localhost:8080/books
content-type: application/json
###

GET http://localhost:8080
content-type: application/json

###

POST http://localhost:8080/books
content-type: application/json

{
    "id": "5",
    "title": "The Hobbit",
    "author": "J. R. R. Tolkien"
}
###

DELETE http://localhost:8080/books/5
content-type: application/json

