basePath: /
definitions:
  github_com_tinwritescode_gin-tin_pkg_model.ErrorResponse:
    properties:
      error:
        example: Error message
        type: string
    type: object
  github_com_tinwritescode_gin-tin_pkg_model.LoginRequest:
    properties:
      password:
        example: password123
        type: string
      username:
        example: newuser
        type: string
    required:
    - password
    - username
    type: object
  github_com_tinwritescode_gin-tin_pkg_model.LoginResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  github_com_tinwritescode_gin-tin_pkg_model.LogoutResponse:
    properties:
      message:
        type: string
    type: object
  github_com_tinwritescode_gin-tin_pkg_model.RefreshTokenRequest:
    properties:
      refresh_token:
        example: refresh_token_value
        type: string
    required:
    - refresh_token
    type: object
  github_com_tinwritescode_gin-tin_pkg_model.RefreshTokenResponse:
    properties:
      access_token:
        type: string
    type: object
  github_com_tinwritescode_gin-tin_pkg_model.RegisterRequest:
    properties:
      password:
        example: password123
        type: string
      username:
        example: newuser
        type: string
    required:
    - password
    - username
    type: object
  github_com_tinwritescode_gin-tin_pkg_model.RegisterResponse:
    properties:
      message:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Authenticate user and return access token
      parameters:
      - description: User login credentials
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/github_com_tinwritescode_gin-tin_pkg_model.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_tinwritescode_gin-tin_pkg_model.LoginResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_tinwritescode_gin-tin_pkg_model.ErrorResponse'
      summary: Login user
      tags:
      - auth
  /logout:
    post:
      consumes:
      - application/json
      description: Invalidate user's access token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_tinwritescode_gin-tin_pkg_model.LogoutResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_tinwritescode_gin-tin_pkg_model.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Logout user
      tags:
      - auth
  /refresh:
    post:
      consumes:
      - application/json
      description: Refresh access token using refresh token
      parameters:
      - description: Refresh token
        in: body
        name: refresh
        required: true
        schema:
          $ref: '#/definitions/github_com_tinwritescode_gin-tin_pkg_model.RefreshTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_tinwritescode_gin-tin_pkg_model.RefreshTokenResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_tinwritescode_gin-tin_pkg_model.ErrorResponse'
      summary: Refresh access token
      tags:
      - auth
  /register:
    post:
      consumes:
      - application/json
      description: Register a new user with username and password
      parameters:
      - description: User registration details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/github_com_tinwritescode_gin-tin_pkg_model.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_tinwritescode_gin-tin_pkg_model.RegisterResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_tinwritescode_gin-tin_pkg_model.ErrorResponse'
      summary: Register a new user
      tags:
      - auth
swagger: "2.0"
